[package]
name = "ironrdp-rdpsnd"
version = "0.6.0"
readme = "README.md"
description = "RDPSND static channel for audio output implemented as described in MS-RDPEA"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[features]
default = []
std = []

[dependencies]
bitflags = "2.9"
tracing = { version = "0.1", features = ["log"] }
ironrdp-svc = { path = "../ironrdp-svc-local", version = "0.5" } # public
ironrdp-core = { path = "../ironrdp-core-local", version = "0.1", features = ["alloc"] }
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6", features = ["alloc"] } # public


