[package]
name = "ironrdp-rdpdr"
version = "0.4.1"
readme = "README.md"
description = "RDPDR channel implementation."
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core-local", version = "0.1" } # public
ironrdp-error = { path = "../ironrdp-error-local", version = "0.1" } # public
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6" } # public
ironrdp-svc = { path = "../ironrdp-svc-local", version = "0.5" } # public
tracing = { version = "0.1", features = ["log"] }
bitflags = "2.9"


