[package]
name = "ironrdp-acceptor"
version = "0.7.0"
readme = "README.md"
description = "State machines to drive an RDP connection acceptance sequence"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core-local", version = "0.1", features = ["alloc"] } # public
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6" } # public
ironrdp-svc = { path = "../ironrdp-svc-local", version = "0.5" } # public
ironrdp-connector = { path = "../ironrdp-connector-local", version = "0.7" } # public
ironrdp-async = { path = "../ironrdp-async-local", version = "0.7" } # public
tracing = { version = "0.1", features = ["log"] }



