[package]
name = "ironrdp-dvc"
version = "0.4.1"
readme = "README.md"
description = "DRDYNVC static channel implementation and traits to implement dynamic virtual channels (local sidecar)"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[features]
default = []
std = []

[dependencies]
ironrdp-core = { path = "../ironrdp-core-local", version = "0.1", features = ["alloc"] } # public
ironrdp-svc = { path = "../ironrdp-svc-local", version = "0.5" } # public
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6", features = ["alloc"] } # public
tracing = { version = "0.1", features = ["log"] }
slab = "0.4"
