[package]
name = "ironrdp-cliprdr"
version = "0.4.0"
readme = "README.md"
description = "CLIPRDR static channel for clipboard implemented as described in MS-RDPECLIP"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core-local", version = "0.1" } # public
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6" } # public
ironrdp-svc = { path = "../ironrdp-svc-local", version = "0.5" } # public
tracing = { version = "0.1", features = ["log"] }
bitflags = "2.9"


