[package]
name = "ironrdp-async"
version = "0.7.0"
readme = "README.md"
description = "Provides `Future`s wrapping the IronRDP state machines conveniently"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
ironrdp-connector = { path = "../ironrdp-connector-local", version = "0.7" } # public
ironrdp-core = "0.1" # public
ironrdp-pdu = { path = "../ironrdp-pdu-local", version = "0.6" } # public
tracing = { version = "0.1", features = ["log"] }
bytes = "1" # public
